# Generated by Django 4.2.7 on 2024-04-19 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionReserva', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='entregado',
            new_name='estado',
        ),
    ]
