# Generated by Django 4.2.7 on 2024-04-23 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionReserva', '0002_rename_entregado_reserva_estado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
